import { useState } from "react";
import { useParams } from "wouter";
import { Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { GateShell, railFor } from "@/components/gate/GateShell";
import { useHarmonizeStream } from "@/hooks/use-harmonize-stream";
import { resumeRun } from "@/lib/api";
import { formatUsd, type ConceptGroup } from "@/types";

/**
 * Gate 1 — Concept groups. THE TRACER'S SCREEN.
 *
 * ROWS ARE POST-SPLIT CONCEPT GROUPS (UI-SPEC §0.1), read from `result.conceptGroups`. Deliberately NOT
 * `previewClusters`: that field is preview run mode's shape — a $0 run that calls no model — and it is no
 * longer Gate 1's row source. A group names its own parent cluster, which is where provenance comes from.
 *
 * THE NAME IS GENERATED, AND SAYS SO. `concept` is what `generate(ideal)` produced, which has already been
 * paid for by the time this screen renders. So it carries a "generated" marker and NO catalog badge, no
 * identifier link and no endorsement — and it is never labelled a GenCDE, which is a different thing minted
 * later and only for `novel` records (UI-SPEC §8).
 *
 * DELIBERATELY THIN. No ledger spine, no sort, no filter, no drag, no carve panel and no coherence column:
 * those are 08-15's, and building half of one here is how two implementations of the same row end up in the
 * tree. This is the tracer — one path, proven end to end, that later plans expand in place.
 *
 * HONEST ABOUT SPEND. Reaching Gate 1 already paid for concept generation, splitting and the coherence
 * judge, so the figure above the Continue button is a REALIZED one. The Continue button buys the assignment
 * step and carries its own amount.
 */

function ConceptGroupRow({ group }: { group: ConceptGroup }) {
  return (
    <li
      data-testid="concept-group"
      data-group-id={group.groupId}
      className="flex items-start justify-between gap-6 border-b border-rule-quiet-on-raised px-6 py-4 last:border-b-0"
    >
      <div className="flex min-w-0 flex-col gap-1">
        <div className="flex min-w-0 items-center gap-2">
          <span className="truncate text-sm font-semibold text-on-raised" title={group.concept}>
            {group.concept || "Unnamed group"}
          </span>
          {/* The generated marker. Icon PLUS text: an icon-only provenance claim is not a claim. */}
          <span
            className="flex shrink-0 items-center gap-1 rounded-pill bg-surface-inset px-2 py-0.5 text-xs text-on-inset-muted"
            title="This name was generated by ddharmon. It is not an NIH catalog element."
          >
            <Sparkles aria-hidden="true" className="h-3 w-3" />
            generated
          </span>
        </div>
        <p className="text-xs text-on-raised-muted">
          from cluster {group.clusterId || "—"} · {group.cohorts.join(", ") || "no cohort recorded"}
        </p>
      </div>
      <span className="shrink-0 text-sm tabular-nums text-on-raised-muted">
        {group.nMembers} {group.nMembers === 1 ? "variable" : "variables"}
      </span>
    </li>
  );
}

export default function Gate1Page() {
  const { jobId = "" } = useParams<{ jobId: string }>();
  const { jobState, error, reconnecting } = useHarmonizeStream(jobId, true, true);
  const [resuming, setResuming] = useState(false);

  const groups: ConceptGroup[] = jobState?.result?.conceptGroups ?? [];
  const costSoFar = jobState?.costSoFar ?? jobState?.result?.cost?.actualUsd ?? 0;
  const clusters = new Set(groups.map((g) => g.clusterId)).size;
  const variables = groups.reduce((n, g) => n + g.nMembers, 0);
  // A run rejoined at a gate rather than walked to. `awaiting_review` is exactly that state: the worker
  // exited, so anything the reviewer is looking at was read back off disk.
  const resumed = jobState?.status === "awaiting_review";

  async function onContinue() {
    setResuming(true);
    try {
      await resumeRun(jobId);
      toast.success("Continuing to Gate 2");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not continue this run");
    } finally {
      setResuming(false);
    }
  }

  return (
    <GateShell
      gate="gate1"
      subhead="Each row is a group of variables that mean the same thing, with the name ddharmon generated for it. Choose which ones go on to be matched against common data elements."
      rail={railFor("gate1", { totalRealized: costSoFar })}
      runName={jobState?.displayName}
      costSoFar={costSoFar}
      resumed={resumed}
    >
      {reconnecting && (
        <p role="status" data-testid="stream-reconnecting" className="text-sm font-semibold text-status-warn">
          Lost contact with the server — reconnecting. The figures below are from the last update, not live.
        </p>
      )}
      {error && (
        <p role="alert" className="text-sm font-semibold text-status-danger">
          {error.message}
        </p>
      )}

      {/* The grouping strip (read-only figures + provenance). No re-clustering control: re-clustering
          invalidates the frozen substrate and strands decisions made against the previous partition, and
          /design already publishes hand-tuning as the REJECTED alternative (D-17). */}
      <p data-testid="grouping-strip" className="text-sm text-on-field-muted">
        <span className="font-semibold text-on-field">
          {groups.length} {groups.length === 1 ? "concept group" : "concept groups"}
        </span>{" "}
        from {clusters} {clusters === 1 ? "cluster" : "clusters"} covering {variables}{" "}
        {variables === 1 ? "variable" : "variables"} — clusters were auto-scaled from your dictionaries, then
        divided into distinct concepts. Reshape a group by moving variables into it, not by re-clustering.
      </p>

      <section className="rounded-card bg-surface-raised shadow-card">
        <h2 className="border-b border-rule-on-raised px-6 py-3 text-xs font-semibold uppercase tracking-eyebrow text-on-raised-muted">
          Concept
        </h2>
        {groups.length === 0 ? (
          <div className="flex flex-col gap-2 px-6 py-8">
            <p className="text-sm font-semibold text-on-raised">No groups formed</p>
            <p className="max-w-[68ch] text-sm text-on-raised-muted">
              Every variable was left unassigned. That usually means the dictionaries share too little text
              to group. Go back to Gate 0 and check the column mapping, or add a dictionary.
            </p>
          </div>
        ) : (
          <ul>
            {groups.map((g) => (
              <ConceptGroupRow key={`${g.clusterId}:${g.groupId}`} group={g} />
            ))}
          </ul>
        )}
      </section>

      {/* Commit bar. The spend above it is REALIZED; the button buys the next step. */}
      <div className="flex items-center justify-between gap-6 rounded-card bg-surface-raised px-6 py-4 shadow-card">
        {/* REALIZED, not a forecast. Two wordings rather than one, because "$0 — this is where spending
            began" is a sentence about a saved replay pretending to be a sentence about a billed run. */}
        {costSoFar > 0 ? (
          <p className="text-sm text-on-raised-muted">
            <span className="font-semibold text-on-raised">
              Already spent to reach this gate: {formatUsd(costSoFar)}
            </span>{" "}
            — naming the concepts, dividing the groups and checking them. That is what the button below
            builds on.
          </p>
        ) : (
          <p className="text-sm text-on-raised-muted">
            <span className="font-semibold text-on-raised">Already spent to reach this gate: nothing</span>{" "}
            — this run is a saved replay, so naming and dividing the groups was not billed to you.
          </p>
        )}
        <Button type="button" onClick={onContinue} disabled={resuming || groups.length === 0}>
          {resuming && <Loader2 aria-hidden="true" className="mr-2 h-4 w-4 animate-spin" />}
          Continue to Gate 2
        </Button>
      </div>
    </GateShell>
  );
}
