#!/usr/bin/env python3
"""Snapshot the seeded sample runs + their exports into static files for a backend-less preview.

Reads the running (seeded) backend at ``--base`` and writes ``frontend/public/static-data/``:
    jobs.json                 — run summaries (stable ids)
    result-<id>.json          — full JobResult per run
    demos.json                — /demos payload
    exports/<id>.<ext>        — every export format, generated by the real backend

A ``VITE_STATIC=1`` frontend build reads these instead of ``/api`` — so the SPA runs fully static
(sample runs, dashboards, exports) with no server, no key. Requires the backend running with seed:
    DDHARMON_UI_SEED=1 ... ./dev.sh   (or serve.sh)
    python scripts/build_static_fixtures.py
"""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "frontend" / "public" / "static-data"

# Stable ids (URL-safe) keyed by a substring of the seeded displayName.
STABLE = {"UKBB": "sample-cross-cohort", "sync": "sample-aou-clsa"}
EXPORTS = {
    "eitl_tsv": "eitl.tsv",
    "decisions_csv": "decisions.csv",
    "records_json": "records.json",
    "notebook_py": "py.ipynb",
    "notebook_r": "r.ipynb",
}


def get(base: str, path: str) -> bytes:
    with urllib.request.urlopen(f"{base}{path}", timeout=30) as r:
        return r.read()


def stable_id(display: str) -> str:
    for key, sid in STABLE.items():
        if key in display:
            return sid
    return display.lower().replace(" ", "-")[:24]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="http://localhost:8000")
    args = ap.parse_args()

    (OUT / "exports").mkdir(parents=True, exist_ok=True)
    jobs = json.loads(get(args.base, "/api/harmonize/jobs"))
    if not jobs:
        raise SystemExit("no jobs — start the backend with DDHARMON_UI_SEED=1 first")

    summaries = []
    for j in jobs:
        cur = j["jobId"]
        sid = stable_id(j["displayName"])
        # Full result, id rewritten to the stable id.
        result = json.loads(get(args.base, f"/api/harmonize/result/{cur}"))
        result["jobId"] = sid
        (OUT / f"result-{sid}.json").write_text(json.dumps(result))
        summary = {k: v for k, v in j.items()}
        summary["jobId"] = sid
        summaries.append(summary)
        # Every export format (generated by the real backend), saved under the stable id.
        for fmt, ext in EXPORTS.items():
            data = get(args.base, f"/api/harmonize/jobs/{cur}/export?format={fmt}")
            (OUT / "exports" / f"{sid}.{ext}").write_bytes(data)
        print(f"  {sid}: result + {len(EXPORTS)} exports")

    (OUT / "jobs.json").write_text(json.dumps(summaries))
    (OUT / "demos.json").write_text(get(args.base, "/api/harmonize/demos").decode())
    print(f"Wrote {OUT.relative_to(REPO)} ({len(summaries)} runs)")


if __name__ == "__main__":
    main()
