import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

/**
 * One retrieved candidate element, as a card the reviewer can pick.
 *
 * A GENERATED ELEMENT IS NEVER PRESENTED AS A CATALOG ONE (UI-SPEC §7.4, §8). A GenCDE carries an explicit
 * "generated by ddharmon, not an NIH catalog element" marker, a distinct treatment, and NO collection
 * badge, NO identifier link and NO endorsement badge — because each of those is a claim that something
 * outside this tool vouched for the element, and nothing did. Never the term "CDV".
 *
 * SELECTION IS THE ACCENT'S JOB (UI-SPEC §5.2.2): the chosen card takes an accent border plus a 3px left
 * rule. Both, not one: a border colour alone is a weak signal on a page of cards, and the rule reads at a
 * glance down a scrolling list.
 *
 * TEAL IS THE COLLECTION BADGE — one of its exactly four reserved uses, and on paper it is the ink form
 * (`--accent-2-on-raised`); the bright form fails contrast on paper and is prohibited there (§5.4).
 *
 * GEOMETRY. The card takes the container radius; the badges and the score inside it never do (§4).
 */

export interface CandidateCardProps {
  /** The element's name. */
  name: string;
  /** The identifier as the catalog spells it — mono, because the machine produced it. */
  identifier?: string;
  /** Retrieval score, shown as work rather than as a verdict. */
  score?: number;
  /** The catalog collection this element belongs to. Absent for a generated element. */
  collection?: string;
  /** An endorsement, e.g. an NIH endorsement level. Absent for a generated element. */
  endorsement?: string;
  /** The participant-facing question text, verbatim where the dictionary has it. */
  question?: string;
  /** The permissible values, as the catalog lists them. */
  values?: string[];
  /** True for an element ddharmon generated because no catalog element fit. */
  generated?: boolean;
  chosen?: boolean;
  /** The model's suggestion — a suggestion, not a decision, and labelled as one. */
  suggested?: boolean;
  onChoose?: () => void;
  className?: string;
}

export function CandidateCard({
  name,
  identifier,
  score,
  collection,
  endorsement,
  question,
  values = [],
  generated = false,
  chosen = false,
  suggested = false,
  onChoose,
  className,
}: CandidateCardProps) {
  return (
    <button
      type="button"
      data-testid="candidate-card"
      data-chosen={chosen}
      data-generated={generated}
      aria-pressed={chosen}
      onClick={onChoose}
      className={cn(
        "flex w-full flex-col gap-2 rounded-card border border-l-4 bg-surface-raised px-6 py-4 text-left",
        chosen
          ? "border-accent-on-raised border-l-accent-action"
          : "border-rule-on-raised border-l-transparent",
        className,
      )}
    >
      <div className="flex flex-wrap items-center gap-2">
        {score !== undefined && (
          <span className="font-mono text-xs font-semibold tabular-nums text-on-raised-muted">
            {score.toFixed(2)}
          </span>
        )}
        {/* A generated element gets the marker and NOTHING that implies external endorsement. */}
        {generated ? (
          <Badge variant="outline" className="rounded-pill">
            GenCDE — generated by ddharmon, not an NIH catalog element
          </Badge>
        ) : (
          <>
            {collection && (
              <Badge variant="outline" className="rounded-pill text-accent-2-on-raised">
                {collection}
              </Badge>
            )}
            {endorsement && (
              <Badge variant="secondary" className="rounded-pill">
                {endorsement}
              </Badge>
            )}
          </>
        )}
        {suggested && (
          <Badge variant="secondary" className="rounded-pill">
            suggested
          </Badge>
        )}
      </div>

      <span className="text-sm font-semibold text-on-raised">{name}</span>
      {/* A generated element carries no identifier LINK: there is nothing outside this tool to link to. */}
      {identifier && !generated && (
        <span className="font-mono text-xs text-on-raised-muted">{identifier}</span>
      )}
      {question && <span className="text-sm text-on-raised-muted">{question}</span>}
      {values.length > 0 && (
        <span className="font-mono text-xs text-on-raised-muted">{values.join(" · ")}</span>
      )}
    </button>
  );
}
